# Generated by Django 5.0.7 on 2024-07-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='Image_url',
        ),
        migrations.AddField(
            model_name='courses',
            name='image_url',
            field=models.ImageField(default='night.jpg', upload_to='course_thumbnails/'),
        ),
    ]
