# Generated by Django 5.0.7 on 2024-07-31 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_courses_image_url_courses_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_one_url', models.ImageField(default='night.jpg', upload_to='course_desc/')),
                ('image_two_url', models.ImageField(default='night.jpg', upload_to='course_desc/')),
                ('course_short_title', models.CharField(max_length=50)),
                ('course_level', models.CharField(max_length=50)),
                ('course_outline', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='courses.courses')),
            ],
        ),
        migrations.CreateModel(
            name='CourseOutline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=100)),
                ('section_content', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlines', to='courses.courses')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
