# Generated by Django 5.0.7 on 2024-07-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursedetails_courseoutline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseoutline',
            options={},
        ),
        migrations.RemoveField(
            model_name='coursedetails',
            name='course_outline',
        ),
        migrations.RemoveField(
            model_name='courseoutline',
            name='section_content',
        ),
        migrations.AddField(
            model_name='courseoutline',
            name='content',
            field=models.TextField(default='daefult text'),
        ),
        migrations.AlterField(
            model_name='courseoutline',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='courseoutline',
            name='section_title',
            field=models.CharField(max_length=200),
        ),
    ]
