# Generated by Django 5.0.7 on 2024-07-31 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_courseoutline_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.courses'),
        ),
    ]
