# Generated by Django 5.0.7 on 2024-08-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_coursedetails_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='intructor_name',
            new_name='instructor_name',
        ),
        migrations.AlterField(
            model_name='courseoutline',
            name='content',
            field=models.TextField(default='Default text'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_tags',
            field=models.CharField(help_text='Values are separated by commas', max_length=200),
        ),
    ]
