# Generated by Django 5.0.7 on 2024-08-02 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_intructor_name_courses_instructor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='courses.courses'),
        ),
    ]
