# Generated by Django 5.0.7 on 2024-08-02 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_coursedetails_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedetails',
            name='image_two_url',
        ),
        migrations.RemoveField(
            model_name='courseoutline',
            name='order',
        ),
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_url', models.URLField()),
                ('outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.courseoutline')),
            ],
        ),
    ]
