# Generated by Django 5.0.7 on 2024-08-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_coursedetails_image_two_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursevideo',
            name='video_url',
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='video_file',
            field=models.FileField(default='night.jpg', upload_to='course_videos/'),
        ),
    ]
