# Generated by Django 5.0.7 on 2024-08-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_coursevideo_video_url_coursevideo_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoutline',
            name='video_file',
            field=models.FileField(default='night.jpg', upload_to='course_videos/'),
        ),
        migrations.AddField(
            model_name='courseoutline',
            name='video_title',
            field=models.CharField(default='Default text', max_length=200),
        ),
        migrations.DeleteModel(
            name='CourseVideo',
        ),
    ]
