# Generated by Django 5.0.7 on 2024-08-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_courseoutline_video_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='course_videos/')),
                ('title', models.CharField(default='Default Title', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='courseoutline',
            name='video_files',
            field=models.ManyToManyField(blank=True, to='courses.videofile'),
        ),
        migrations.DeleteModel(
            name='CourseVideo',
        ),
    ]
