# Generated by Django 5.0.7 on 2024-08-02 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_videofile_courseoutline_video_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoutline',
            name='video_files',
        ),
        migrations.AlterField(
            model_name='courseoutline',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_outlines', to='courses.courses'),
        ),
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_file', models.FileField(upload_to='course_videos/')),
                ('outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_videos', to='courses.courseoutline')),
            ],
        ),
        migrations.DeleteModel(
            name='VideoFile',
        ),
    ]
