# Generated by Django 5.0.7 on 2024-08-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_remove_courseoutline_video_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideo',
            name='video_content',
            field=models.TextField(default='Default text'),
        ),
    ]
