# Generated by Django 5.0.7 on 2024-08-03 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_remove_comment_content_comment_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
